### ISSUE TITLE
Sample with express

### ISSUE THREAD

**Issue by AhmadEl-Banna** [fabiospampinato/mongease-graphql-builder#1]
I'm little confused about how to expose this to the express , 
would you please add an example to the Doc

**Comment by fabiospampinato** [comment]
@AhmadEl-Banna you can find an example of how this is used [here](https://github.com/fabiospampinato/TRAM/tree/d14bbbf1416728791335620490ea75afdc255e1c). 

I'm probably not going to maintain this project though, you should probably use some other solution.
